baseurl = "/"
languageCode = "en-US"
title = "Alicia"
# Enable comments by entering your Disqus shortname
disqusShortname = "aliciaschep"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Alicia Schep"
  description = "Personal website and blog of Alicia Schep, a human data scientist."
  
  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "https://cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "javascript"]
  highlightjsTheme = "github"
  
  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "AliciaSchep"
  Twitter       = "AliciaSchep"
  LinkedIn      = "AliciaSchep"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "software"
  identifier = "software"
  weight = 200
  url = "/software/"
[[menu.main]]
  name = "publications"
  identifier = "publications"
  weight = 300
  url = "https://scholar.google.com/citations?hl=en&user=8VWyFLsAAAAJ"
